# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FRSNSHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FRSNSHelper
  pod 'Firebase/Messaging'
  pod 'FBSDKLoginKit'
  pod 'FacebookShare'
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/YouTube'
  pod 'naveridlogin-sdk-ios'

end
